Azure integration
ow2-proactive/scheduling-abstraction-layer pull request #118
Opened 2024-12-27 08:38 UTC by mbenguig

2024-12-27 16:21 UTC, ankicabarisic requested changes
please resolve the conflicts with reconfiguration and write what was fixed by this PR and how it can be tested

2024-12-27 18:16 UTC, fviale commented
@mbenguig 
This is a lot of commits, are you sure your fork is synced with the master repository ?

As a side note, I had a lot of issues with cherry-picking this project when releasing 14.0.2 . Please ensure that when merging pull requests commits are squashed. If there are too many commits and squash is too complicated, just do a clean fork and clean pull request

2025-01-03 12:01 UTC, fviale commented
@mbenguig your pull request has too many commits and your fork is not properly synchronized with the master.

Please do a clean fork and clean pull request

You can obtain this pull request diff by using:
https://patch-diff.githubusercontent.com/raw/ow2-proactive/scheduling-abstraction-layer/pull/118.diff

2025-01-03 12:31 UTC, mbenguig commented
> @mbenguig your pull request has too many commits and your fork is not properly synchronized with the master.
> 
> Please do a clean fork and clean pull request
> 
> You can obtain this pull request diff by using: https://patch-diff.githubusercontent.com/raw/ow2-proactive/scheduling-abstraction-layer/pull/118.diff

Rather than  a squash merge ? Ok

2025-01-03 12:31 UTC, mbenguig commented
> please resolve the conflicts with reconfiguration and write what was fixed by this PR and how it can be tested

Resolved

2025-01-03 12:45 UTC, ankicabarisic commented
testing and problems i reported on slack
i would prefer that you create new branch from master, and apply your changes there as it is only several lines of code in SAL and see how it behaves then
when i pull this branch it is not having latest changes on master branch so it might impact the different behaviour then the one you are having, also the failing deleteCluster might be due to fact the changes from begining of december are not there

2025-01-03 12:46 UTC, ankicabarisic commented on sal-service/src/main/java/org/ow2/proactive/sal/service/service/TaskBuilder.java
> -            case OPENSTACK:
you delete openstack here?

2025-01-04 17:07 UTC, mbenguig commented on sal-service/src/main/java/org/ow2/proactive/sal/service/service/TaskBuilder.java
> -            case OPENSTACK:
openstack and default branches are equivalent but ok to re-add the openstack branch

2025-01-04 17:15 UTC, mbenguig commented
Will be replaced by another PR.

2025-01-04 17:15 UTC, closed without merging